In [4]:
import numpy as np

In [6]:
a = np.array([1,2,3])

In [10]:
print(np.shape(a))

(3,)


In [17]:
b = np.array([[1,2,3], [4,5,6]])
np.shape(b)

(2, 3)

In [18]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b[1,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [22]:
c = np.zeros((3,3))

In [25]:
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
d = np.ones((3,3))

In [27]:
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
ok = np.array(['ab', 'bbdfgfdg'])

In [34]:
ok.dtype

dtype('<U8')